# Generated by Django 4.2.1 on 2023-05-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('descripcion', models.CharField(max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de curso',
                'verbose_name_plural': 'Categorias de cursos',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250, null=True)),
                ('nombre', models.IntegerField(null=True)),
                ('mensaje', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Consulta de usuario',
                'verbose_name_plural': 'Consultas de usuarios',
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=80, null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('calificacion', models.FloatField(default=None, null=True)),
                ('fecha_alta_curso', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen_url', models.URLField(max_length=500, null=True)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_categoria', to='educando_ecommerce.categoria')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, null=True)),
                ('alta_rol', models.DateTimeField(null=True)),
                ('baja_rol', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuarios',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250, null=True)),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('apellido', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
                ('fecha_alta_usuario', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_baja_usuario', models.DateTimeField(blank=True, default=None, null=True)),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_rol', to='educando_ecommerce.rol')),
            ],
            options={
                'verbose_name': 'Usuario registrado mediante el front',
                'verbose_name_plural': 'Usuarios registrados mediante el front',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='MisCurso',
            fields=[
                ('id_mis_curso', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_url', models.URLField(max_length=500, null=True)),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_curso_cursos', to='educando_ecommerce.curso')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educando_ecommerce.usuario')),
            ],
            options={
                'verbose_name': 'Mi Curso comprado',
                'verbose_name_plural': 'Mis Cursos comprados',
                'db_table': 'mis_curso',
            },
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id_foro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('mensaje', models.CharField(max_length=500, null=True)),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foro_rol', to='educando_ecommerce.rol')),
                ('id_usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educando_ecommerce.usuario')),
            ],
            options={
                'verbose_name': 'Foro de consulta',
                'verbose_name_plural': 'Foros de consultas',
                'db_table': 'foro',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=80, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('total_suma', models.FloatField(null=True)),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educando_ecommerce.curso')),
            ],
            options={
                'verbose_name': 'Curso seleccionado para comprar',
                'verbose_name_plural': 'Cursos seleccionados para comprar',
                'db_table': 'carrito',
            },
        ),
    ]
